# For more information: https://www.digitalocean.com/community/tutorials/how-to-containerize-a-laravel-application-for-development-with-docker-compose-on-ubuntu-18-04
services:
    app:
        build:
            args:
                user: lazo
                uid: 1000
            context: ./docker/other
            dockerfile: Dockerfile
        image: lazoappback
        container_name: lazoappback-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
        - ./:/var/www
        networks:
        - lazoappback

    nginx:
        image: nginx:1.24-alpine
        container_name: lazoappback-nginx
        restart: unless-stopped
        ports:
        - 8000:8000
        volumes:
        - ./:/var/www
        - ./docker/other/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/other/nginx:/etc/nginx/conf.d
        - /root/crt:/etc/nginx/certs
        - ../lazocerts:/etc/nginx/certs
        networks:
        - lazoappback

networks:
    lazoappback:
        driver: bridge